apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
      - name: wazuh-manager
        image: wazuh/wazuh:4.8.0
        ports:
        - containerPort: 1514
          protocol: UDP
        - containerPort: 1515
        - containerPort: 55000
        - containerPort: 514
          protocol: UDP
        env:
        - name: WAZUH_MANAGER
          value: "yes"
        volumeMounts:
        - name: wazuh-config
          mountPath: /var/ossec/etc
        - name: wazuh-logs
          mountPath: /var/ossec/logs
      volumes:
      - name: wazuh-config
        emptyDir: {}
      - name: wazuh-logs
        emptyDir: {}
